AllCops:
  CacheRootDirectory: tmp
  DisplayCopNames: true
  Exclude:
    - .git/**/*
    - gemfiles/vendor/**/*
    - vendor/**/*
  TargetRubyVersion: 2.1

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

Lint/AssignmentInCondition:
  Enabled: false

Lint/EndAlignment:
  Enabled: variable

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ClassVars:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyLines:
  Exclude:
    - 'lib/active_record_shards-3-2.rb'
    - 'lib/active_record_shards-4-0.rb'
    - 'lib/active_record_shards-4-1.rb'
    - 'lib/active_record_shards-5-0.rb'

Style/FileName:
  Exclude:
    - 'lib/active_record_shards-3-2.rb'
    - 'lib/active_record_shards-4-0.rb'
    - 'lib/active_record_shards-4-1.rb'
    - 'lib/active_record_shards-5-0.rb'
    - 'lib/active_record_shards/connection_switcher-4-0.rb'
    - 'lib/active_record_shards/connection_switcher-5-0.rb'

Style/FormatString:
  EnforcedStyle: percent

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/IfUnlessModifier:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/IndentationWidth:
  Width: 2

Style/NumericLiterals:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false
